; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:native]
platform = native
test_framework = unity
build_flags =
    -std=c++17
    -I test/test_gateway/mocks   ; mocks found BEFORE system headers
    -I lib/littlefs_native
    -DMG_ENABLE_LOG=0                   ; silence mongoose in tests
build_src_filter =
    -<*>                                ; ignore all source files
[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
build_flags = -I include
monitor_speed = 115200
