; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
src_dir = FactoryTest_wMenu

[env:esp32dev]
platform = espressif32@^6.12.0
board = esp32dev
board_build.filesystem = littlefs
framework = arduino
monitor_speed = 115200
build_flags =
	-DELEGANTOTA_USE_ASYNC_WEBSERVER=1
lib_deps =
	marcoschwartz/LiquidCrystal_I2C@^1.1.4
	dfrobot/DFRobotDFPlayerMini@^1.0.6
	esp32async/AsyncTCP@^3.4.10
	esp32async/ESPAsyncWebServer@^3.7.3
	ayushsharma82/ElegantOTA@^3.1.7
	mathertel/OneButton@^2.6.2
